import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
const root=document.getElementById('game'),speedEl=document.getElementById('speed');
const scene=new THREE.Scene();scene.background=new THREE.Color(0x071019);scene.fog=new THREE.Fog(0x071019,70,230);
const camera=new THREE.PerspectiveCamera(65,innerWidth/innerHeight,.1,500);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;root.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0x9fd8ff,0x11151c,1.5));const sun=new THREE.DirectionalLight(0xffffff,2.2);sun.position.set(-60,100,40);sun.castShadow=true;scene.add(sun);
const roadMat=new THREE.MeshStandardMaterial({color:0x252a31,roughness:.88}),grassMat=new THREE.MeshStandardMaterial({color:0x15241c,roughness:1}),wallMat=new THREE.MeshStandardMaterial({color:0x26323d,roughness:.7}),rampMat=new THREE.MeshStandardMaterial({color:0x384a58,roughness:.65});
function box(x,y,z,sx,sy,sz,mat,rot=0){const m=new THREE.Mesh(new THREE.BoxGeometry(sx,sy,sz),mat);m.position.set(x,y,z);m.rotation.y=rot;m.castShadow=true;m.receiveShadow=true;scene.add(m);return m}
box(0,-.7,0,220,1,180,grassMat);for(let x=-100;x<=100;x+=20)for(let z=-80;z<=80;z+=20){if(Math.abs(x)<45&&Math.abs(z)<40)continue;box(x,2,z,12,4,12,wallMat,Math.random()*Math.PI)}
function road(x,z,w,d,r=0){box(x,.05,z,w,.18,d,roadMat,r)}road(0,0,125,18);road(45,-30,18,75);road(-45,30,18,75);road(0,65,110,18);road(0,-65,110,18);road(0,0,18,125,Math.PI/2);road(75,0,45,18);road(-75,0,45,18);
function ramp(x,z,r=0){const m=box(x,2.2,z,12,4.5,22,rampMat,r);m.geometry.translate(0,-1.7,-6)}ramp(15,-65);ramp(-15,65,Math.PI);ramp(75,0,-Math.PI/2);ramp(-75,0,Math.PI/2);
const car=new THREE.Group();const body=new THREE.Mesh(new THREE.BoxGeometry(2.2,.65,4),new THREE.MeshStandardMaterial({color:0xdfe9f0,metalness:.55,roughness:.25}));body.position.y=.9;car.add(body);const cabin=new THREE.Mesh(new THREE.BoxGeometry(1.65,.55,1.7),new THREE.MeshStandardMaterial({color:0x172432}));cabin.position.set(0,1.38,-.2);car.add(cabin);for(const x of [-1,1])for(const z of [-1.25,1.25]){const w=new THREE.Mesh(new THREE.CylinderGeometry(.42,.42,.25,16),new THREE.MeshStandardMaterial({color:0x08090b}));w.rotation.z=Math.PI/2;w.position.set(x*1.05,.55,z);car.add(w)}car.position.set(0,.1,0);scene.add(car);
const keys={};addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(e.key.toLowerCase()))e.preventDefault();if(e.key.toLowerCase()==='r')reset()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
let speed=0,air=0,last=performance.now();function reset(){car.position.set(0,.1,0);car.rotation.y=0;speed=0;air=0}function update(dt){const gas=keys.w||keys.arrowup,brake=keys.s||keys.arrowdown,left=keys.a||keys.arrowleft,right=keys.d||keys.arrowright,hand=keys[' '];speed+=(gas?34:brake?-22:0)*dt;speed*=Math.pow(hand?.965:.985,dt*60);speed=THREE.MathUtils.clamp(speed,-18,52);const steer=(right?1:0)-(left?1:0);car.rotation.y-=.95*(speed/28)*steer*dt*(hand?1.7:1);const f=new THREE.Vector3(Math.sin(car.rotation.y),0,Math.cos(car.rotation.y)),side=new THREE.Vector3(f.z,0,-f.x);let lateral=0;lateral*=hand?.82:.18;car.position.addScaledVector(f.multiplyScalar(speed).add(side.multiplyScalar(lateral)),dt);if(car.position.y>.11){air-=20*dt;car.position.y+=air*dt;if(car.position.y<=.1){car.position.y=.1;air=0}}car.position.x=THREE.MathUtils.clamp(car.position.x,-106,106);car.position.z=THREE.MathUtils.clamp(car.position.z,-86,86);speedEl.textContent=Math.round(Math.abs(speed)*3.6)}function loop(now){requestAnimationFrame(loop);const dt=Math.min((now-last)/1000,.033);last=now;update(dt);const behind=new THREE.Vector3(-Math.sin(car.rotation.y)*10,6.2,-Math.cos(car.rotation.y)*10);camera.position.lerp(car.position.clone().add(behind),.12);camera.lookAt(car.position.x,car.position.y+1,car.position.z);renderer.render(scene,camera)}addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});loop(performance.now());