const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');const scoreEl=document.getElementById('score'),bestEl=document.getElementById('best'),speedEl=document.getElementById('speed'),overlay=document.getElementById('overlay'),title=document.getElementById('overlayTitle'),text=document.getElementById('overlayText'),startBtn=document.getElementById('startBtn'),soundBtn=document.getElementById('soundBtn');
let keys={},running=false,score=0,best=Number(localStorage.neonRushBest||0),last=0,spawn=0,shake=0,sound=true;let player={x:450,y:280,r:13,vx:0,vy:0};let orb={x:650,y:280,r:8};let enemies=[];bestEl.textContent=best;
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(e.key.toLowerCase()))e.preventDefault()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
canvas.addEventListener('pointermove',e=>{if(e.pointerType==='touch'&&running){const r=canvas.getBoundingClientRect();player.x=(e.clientX-r.left)*canvas.width/r.width;player.y=(e.clientY-r.top)*canvas.height/r.height}});
startBtn.onclick=start;soundBtn.onclick=()=>{sound=!sound;soundBtn.textContent=sound?'🔊':'🔇'};
function start(){score=0;enemies=[];player={x:450,y:280,r:13,vx:0,vy:0};placeOrb();running=true;overlay.classList.add('hidden');last=performance.now();requestAnimationFrame(loop)}
function placeOrb(){orb={x:35+Math.random()*830,y:35+Math.random()*490,r:8}}
function addEnemy(){const side=Math.floor(Math.random()*4);let x=side<2?(side?865:35):35+Math.random()*830,y=side<2?35+Math.random()*490:(side?525:35);enemies.push({x,y,r:10+Math.random()*5,s:55+Math.random()*35+score*.035})}
function beep(freq=500){if(!sound)return;try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.frequency.value=freq;g.gain.value=.025;o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.06)}catch{}}
function loop(now){if(!running)return;const dt=Math.min((now-last)/1000,.033);last=now;update(dt);draw();requestAnimationFrame(loop)}
function update(dt){let ax=0,ay=0;if(keys.w||keys.arrowup)ay--;if(keys.s||keys.arrowdown)ay++;if(keys.a||keys.arrowleft)ax--;if(keys.d||keys.arrowright)ax++;const len=Math.hypot(ax,ay)||1;player.vx+=ax/len*900*dt;player.vy+=ay/len*900*dt;player.vx*=Math.pow(.001,dt);player.vy*=Math.pow(.001,dt);player.x+=player.vx*dt;player.y+=player.vy*dt;player.x=Math.max(player.r,Math.min(canvas.width-player.r,player.x));player.y=Math.max(player.r,Math.min(canvas.height-player.r,player.y));
spawn-=dt;if(spawn<=0){addEnemy();spawn=Math.max(.35,1.25-score*.006)}for(const e of enemies){const dx=player.x-e.x,dy=player.y-e.y,d=Math.hypot(dx,dy)||1;e.x+=dx/d*e.s*dt;e.y+=dy/d*e.s*dt;if(d<player.r+e.r){gameOver();return}}enemies=enemies.filter(e=>e.x>-30&&e.x<930&&e.y>-30&&e.y<590);
if(Math.hypot(player.x-orb.x,player.y-orb.y)<player.r+orb.r+3){score++;scoreEl.textContent=score;placeOrb();beep(700);shake=5}speedEl.textContent=(1+score*.02).toFixed(1)+'x';shake=Math.max(0,shake-dt*20)}
function gameOver(){running=false;best=Math.max(best,score);localStorage.neonRushBest=best;bestEl.textContent=best;title.textContent='GAME OVER';text.innerHTML=`You scored <b>${score}</b>. The hunters got you.<br>Think you can beat ${best}?`;startBtn.textContent='PLAY AGAIN';overlay.classList.remove('hidden');beep(130)}
function draw(){ctx.save();ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);const g=ctx.createLinearGradient(0,0,0,canvas.height);g.addColorStop(0,'#080a18');g.addColorStop(1,'#03040b');ctx.fillStyle=g;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='#ffffff08';ctx.lineWidth=1;for(let x=0;x<canvas.width;x+=45){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,canvas.height);ctx.stroke()}for(let y=0;y<canvas.height;y+=45){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(canvas.width,y);ctx.stroke()}
ctx.shadowBlur=25;ctx.shadowColor='#7cf7ff';ctx.fillStyle='#7cf7ff';ctx.beginPath();ctx.arc(orb.x,orb.y,orb.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(orb.x-2,orb.y-2,2,0,Math.PI*2);ctx.fill();
for(const e of enemies){ctx.shadowBlur=18;ctx.shadowColor='#ff3b70';ctx.fillStyle='#ff3b70';ctx.beginPath();ctx.arc(e.x,e.y,e.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}ctx.shadowBlur=24;ctx.shadowColor='#7cf7ff';ctx.fillStyle='#e9ffff';ctx.beginPath();ctx.arc(player.x,player.y,player.r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#7cf7ff';ctx.beginPath();ctx.moveTo(player.x,player.y-18);ctx.lineTo(player.x-7,player.y+5);ctx.lineTo(player.x+7,player.y+5);ctx.closePath();ctx.fill();ctx.restore()}
