import * as THREE from './three.js';
const root=document.getElementById('game'),speedEl=document.getElementById('speed');
const scene=new THREE.Scene();scene.background=new THREE.Color(0x87ceeb);
const camera=new THREE.PerspectiveCamera(65,innerWidth/innerHeight,.1,500);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setSize(innerWidth,innerHeight);root.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xffffff,0x666666,2));
const ground=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.MeshStandardMaterial({color:0x777777}));ground.rotation.x=-Math.PI/2;scene.add(ground);
const car=new THREE.Group();
const body=new THREE.Mesh(new THREE.BoxGeometry(2.2,.65,4),new THREE.MeshStandardMaterial({color:0xff3030,metalness:.25,roughness:.3}));body.position.y=.75;car.add(body);
const roof=new THREE.Mesh(new THREE.BoxGeometry(1.65,.55,1.7),new THREE.MeshStandardMaterial({color:0x2266ff,metalness:.15,roughness:.25}));roof.position.set(0,1.25,-.15);car.add(roof);
for(const x of [-1,1])for(const z of [-1.25,1.25]){const w=new THREE.Mesh(new THREE.CylinderGeometry(.42,.42,.3,16),new THREE.MeshStandardMaterial({color:0x111111}));w.rotation.z=Math.PI/2;w.position.set(x*1.05,.42,z);car.add(w)}
car.position.y=.05;scene.add(car);
const keys={};addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.key.toLowerCase()==='r'){car.position.set(0,.05,0);car.rotation.y=0;speed=0}});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
let speed=0,last=performance.now();function update(dt){const gas=keys.w||keys.arrowup,brake=keys.s||keys.arrowdown,left=keys.a||keys.arrowleft,right=keys.d||keys.arrowright;speed+=(gas?30:brake?-20:0)*dt;speed*=.985;speed=THREE.MathUtils.clamp(speed,-15,45);const steer=(right?1:0)-(left?1:0);car.rotation.y-=steer*speed*.025*dt;car.position.x+=Math.sin(car.rotation.y)*speed*dt;car.position.z+=Math.cos(car.rotation.y)*speed*dt;speedEl.textContent=Math.round(Math.abs(speed)*3.6)}function loop(t){requestAnimationFrame(loop);const dt=Math.min((t-last)/1000,.033);last=t;update(dt);const behind=new THREE.Vector3(-Math.sin(car.rotation.y)*9,5,-Math.cos(car.rotation.y)*9);camera.position.lerp(car.position.clone().add(behind),.12);camera.lookAt(car.position.x,car.position.y+.8,car.position.z);renderer.render(scene,camera)}addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});loop(performance.now());